'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsUcolProduccion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://siceuc2.ucol.mx/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private consultaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private fintransaccionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cancelartransaccionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private generarReferenciaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.pagos.My.MySettings.Default.pagos_wsUcolProduccion_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event consultaCompleted As consultaCompletedEventHandler
        
        '''<remarks/>
        Public Event fintransaccionCompleted As fintransaccionCompletedEventHandler
        
        '''<remarks/>
        Public Event cancelartransaccionCompleted As cancelartransaccionCompletedEventHandler
        
        '''<remarks/>
        Public Event generarReferenciaCompleted As generarReferenciaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://siceuc2.ucol.mx/consulta", RequestNamespace:="http://siceuc2.ucol.mx/", ResponseNamespace:="http://siceuc2.ucol.mx/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consulta(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer) As respuesta
            Dim results() As Object = Me.Invoke("consulta", New Object() {usuario, contrasenia, referencia, tienda})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer)
            Me.consultaAsync(usuario, contrasenia, referencia, tienda, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer, ByVal userState As Object)
            If (Me.consultaOperationCompleted Is Nothing) Then
                Me.consultaOperationCompleted = AddressOf Me.OnconsultaOperationCompleted
            End If
            Me.InvokeAsync("consulta", New Object() {usuario, contrasenia, referencia, tienda}, Me.consultaOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaCompleted(Me, New consultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://siceuc2.ucol.mx/fintransaccion", RequestNamespace:="http://siceuc2.ucol.mx/", ResponseNamespace:="http://siceuc2.ucol.mx/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function fintransaccion(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer, ByVal monto As Decimal) As respuesta
            Dim results() As Object = Me.Invoke("fintransaccion", New Object() {usuario, contrasenia, referencia, tienda, monto})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub fintransaccionAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer, ByVal monto As Decimal)
            Me.fintransaccionAsync(usuario, contrasenia, referencia, tienda, monto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub fintransaccionAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer, ByVal monto As Decimal, ByVal userState As Object)
            If (Me.fintransaccionOperationCompleted Is Nothing) Then
                Me.fintransaccionOperationCompleted = AddressOf Me.OnfintransaccionOperationCompleted
            End If
            Me.InvokeAsync("fintransaccion", New Object() {usuario, contrasenia, referencia, tienda, monto}, Me.fintransaccionOperationCompleted, userState)
        End Sub
        
        Private Sub OnfintransaccionOperationCompleted(ByVal arg As Object)
            If (Not (Me.fintransaccionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent fintransaccionCompleted(Me, New fintransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://siceuc2.ucol.mx/cancelartransaccion", RequestNamespace:="http://siceuc2.ucol.mx/", ResponseNamespace:="http://siceuc2.ucol.mx/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function cancelartransaccion(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer) As respuesta
            Dim results() As Object = Me.Invoke("cancelartransaccion", New Object() {usuario, contrasenia, referencia, tienda})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cancelartransaccionAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer)
            Me.cancelartransaccionAsync(usuario, contrasenia, referencia, tienda, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cancelartransaccionAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal referencia As String, ByVal tienda As Integer, ByVal userState As Object)
            If (Me.cancelartransaccionOperationCompleted Is Nothing) Then
                Me.cancelartransaccionOperationCompleted = AddressOf Me.OncancelartransaccionOperationCompleted
            End If
            Me.InvokeAsync("cancelartransaccion", New Object() {usuario, contrasenia, referencia, tienda}, Me.cancelartransaccionOperationCompleted, userState)
        End Sub
        
        Private Sub OncancelartransaccionOperationCompleted(ByVal arg As Object)
            If (Not (Me.cancelartransaccionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cancelartransaccionCompleted(Me, New cancelartransaccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://siceuc2.ucol.mx/generarReferencia", RequestNamespace:="http://siceuc2.ucol.mx/", ResponseNamespace:="http://siceuc2.ucol.mx/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function generarReferencia(ByVal usuario As String, ByVal contrasenia As String, ByVal monto As Decimal) As respuesta
            Dim results() As Object = Me.Invoke("generarReferencia", New Object() {usuario, contrasenia, monto})
            Return CType(results(0),respuesta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub generarReferenciaAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal monto As Decimal)
            Me.generarReferenciaAsync(usuario, contrasenia, monto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub generarReferenciaAsync(ByVal usuario As String, ByVal contrasenia As String, ByVal monto As Decimal, ByVal userState As Object)
            If (Me.generarReferenciaOperationCompleted Is Nothing) Then
                Me.generarReferenciaOperationCompleted = AddressOf Me.OngenerarReferenciaOperationCompleted
            End If
            Me.InvokeAsync("generarReferencia", New Object() {usuario, contrasenia, monto}, Me.generarReferenciaOperationCompleted, userState)
        End Sub
        
        Private Sub OngenerarReferenciaOperationCompleted(ByVal arg As Object)
            If (Not (Me.generarReferenciaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent generarReferenciaCompleted(Me, New generarReferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://siceuc2.ucol.mx/")>  _
    Partial Public Class respuesta
        
        Private respuestaField As Short
        
        Private txtrespuestaField As String
        
        Private codigoField As String
        
        '''<comentarios/>
        Public Property Respuesta() As Short
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property txtrespuesta() As String
            Get
                Return Me.txtrespuestaField
            End Get
            Set
                Me.txtrespuestaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub consultaCompletedEventHandler(ByVal sender As Object, ByVal e As consultaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub fintransaccionCompletedEventHandler(ByVal sender As Object, ByVal e As fintransaccionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class fintransaccionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub cancelartransaccionCompletedEventHandler(ByVal sender As Object, ByVal e As cancelartransaccionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cancelartransaccionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub generarReferenciaCompletedEventHandler(ByVal sender As Object, ByVal e As generarReferenciaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class generarReferenciaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuesta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuesta)
            End Get
        End Property
    End Class
End Namespace
